export const RECEIVE_INPUT_FILE = "RECEIVE_INPUT_FILE";
export const REQUEST_INPUT_FILE = "REQUEST_INPUT_FILE";
export const SELECT_SUBREDDIT = "SELECT_SUBREDDIT";
export const INVALIDATE_INPUT = "INVALIDATE_INPUT";
export const INVALIDATE_SUBREDDIT = "INVALIDATE_SUBREDDIT";
export const REQUEST_POSTS = "REQUEST_POSTS";
export const RECEIVE_POSTS = "RECEIVE_POSTS";
